// Menu sourced from royalfrenchcrepe.com — tiers (Classic / Premium / Royal /
// Caviar) and per-crêpe ingredient lists taken from the original menu page's
// hover tooltips. No prices: catering is fully custom-quoted.

export const menuCategories = [
  { id: "classic", label: "Classic", french: "Les Classiques" },
  { id: "premium", label: "Premium", french: "Les Premiums" },
  { id: "royal", label: "Royal", french: "Les Royales" },
  { id: "caviar", label: "Caviar", french: "La Collection Royale" },
  { id: "drinks", label: "Coffee & Tea", french: "Boissons" },
];

export const menu = {
  classic: [
    { name: "La Parisienne", type: "Sweet", img: "/images/menu/la-parisienne.jpg",
      ingredients: ["Nutella", "Powdered sugar", "Chocolate syrup"] },
    { name: "Coco Chocolat", type: "Sweet", img: "/images/menu/coco-chocolat.jpg",
      ingredients: ["Nutella", "Shredded coconut", "Nuts", "Chocolate syrup", "Whipped cream"] },
    { name: "La Classique", type: "Sweet", img: "/images/menu/la-classique.jpg",
      ingredients: ["Cane sugar", "Powdered sugar"] },
    { name: "The New York", type: "Sweet", img: "/images/menu/the-new-york.jpg",
      ingredients: ["Peanut butter", "Powdered sugar", "Chocolate syrup"] },
    { name: "La Dame Blanche", type: "Sweet", img: "/images/menu/la-dame-blanche.jpg",
      ingredients: ["Nutella", "Marshmallows", "Powdered sugar", "Nuts", "Shredded coconut", "Whipped cream", "Chocolate syrup"] },
    { name: "Crunchy Nutella", type: "Sweet", img: "/images/menu/crunchy-nutella.jpg",
      ingredients: ["Nutella", "Nuts", "Powdered sugar", "Whipped cream", "Chocolate syrup"] },
    { name: "Délice de Miel", type: "Sweet", img: "/images/menu/delice-de-miel.jpg",
      ingredients: ["Honey", "Powdered sugar"] },
    { name: "La Forestière", type: "Sweet", img: "/images/menu/la-forestiere.jpg",
      ingredients: ["Walnuts", "Nutella", "Whipped cream", "Powdered sugar"] },
    { name: "La Médiéval", type: "Sweet", img: "/images/menu/la-medieval.jpg",
      ingredients: ["Walnuts", "Nutella", "Peanut butter", "Powdered sugar"] },
    { name: "La Villageoise", type: "Savory", img: "/images/menu/la-villageoise.jpg",
      ingredients: ["Ham", "Cheese"] },
    { name: "La Fromagère", type: "Savory", img: "/images/menu/la-fromagere.jpg",
      ingredients: ["Cheese", "Cheese", "More cheese"] },
  ],
  premium: [
    { name: "Chicken & Cheese", type: "Savory", tag: "Best Seller", img: "/images/menu/chicken-cheese.jpg",
      ingredients: ["Chicken", "Cheese", "Salad"] },
    { name: "Salame & Brie", type: "Savory", tag: "New", img: "/images/menu/salame-brie.jpg",
      ingredients: ["Salami", "Brie cheese", "Salad", "Tomatoes"] },
    { name: "La Jardinière", type: "Savory", img: "/images/menu/la-jardiniere.jpg",
      ingredients: ["Ham", "Tomatoes", "Salad", "Avocado", "Cheese (optional)"] },
    { name: "La Gourmande", type: "Sweet", tag: "Best Seller", img: "/images/menu/la-gourmande.jpg",
      ingredients: ["Nutella", "Strawberries", "Jam (if asked)", "Banana", "Powdered sugar", "Chocolate syrup", "Whipped cream", "Nuts"] },
    { name: "La Patissière", type: "Sweet", img: "/images/menu/la-patissiere.jpg",
      ingredients: ["Strawberries", "Banana", "Whipped cream", "Powdered sugar", "Nuts", "Chocolate syrup"] },
    { name: "La Saison Fruitée", type: "Sweet", img: "/images/menu/la-saison-fruitee.jpg",
      ingredients: ["Seasonal fruit", "Cane sugar", "Powdered sugar"] },
    { name: "Banane du Nord", type: "Sweet", img: "/images/menu/banane-du-nord.jpg",
      ingredients: ["Apple or banana", "Strawberries or raspberries", "Nuts", "1 scoop ice cream", "Powdered sugar", "Chocolate syrup"] },
    { name: "The America", type: "Sweet", img: "/images/menu/the-america.jpg",
      ingredients: ["Nutella", "Banana"] },
    { name: "Our Sweety Fruity", type: "Sweet", img: "/images/menu/sweety-fruity.jpg",
      ingredients: ["Fresh fruits", "Whipped cream", "Toppings"] },
  ],
  royal: [
    { name: "La Bretonne", type: "Savory", tag: "Best Seller", img: "/images/menu/la-bretonne.jpg",
      ingredients: ["Salmon or ham", "Goat cheese", "Cheddar", "Lemon", "Egg", "Salad", "Tomatoes", "Nuts", "Avocado"] },
    { name: "La Fermière", type: "Savory", img: "/images/menu/la-fermiere.jpg",
      ingredients: ["Ham", "Goat cheese", "Eggs", "Avocado"] },
    { name: "Mushrooms & Chicken", type: "Savory", tag: "New", img: "/images/menu/mushrooms-chicken.jpg",
      ingredients: ["Mushrooms", "Chicken", "Avocado", "Salad", "Goat cheese", "French white cream", "Tomatoes"] },
    { name: "L'Atlantic", type: "Savory", img: "/images/menu/latlantic.jpg",
      ingredients: ["Smoked salmon", "Tomatoes", "Lemon"] },
    { name: "Marie Antoinette", type: "Sweet", tag: "Best Seller", img: "/images/menu/marie-antoinette.jpg",
      ingredients: ["Nutella", "Shredded coconut", "Strawberries", "Whole banana", "Nuts & almonds", "3 scoops natural ice cream", "Whipped cream", "Strawberry or chocolate syrup"] },
    { name: "Louis XVI", type: "Sweet", img: "/images/menu/louis-xvi.jpg",
      ingredients: ["Strawberries", "Whole banana", "Shredded coconut", "Nuts & almonds", "2 scoops ice cream", "Whipped cream", "Syrup"] },
    { name: "Fraîcheur du Nord", type: "Sweet", img: "/images/menu/fraicheur-du-nord.jpg",
      ingredients: ["Blueberries", "Strawberries or raspberries", "Shredded coconut", "1 scoop ice cream", "Powdered sugar", "Strawberry syrup"] },
  ],
  caviar: [
    { name: "La Royale Ossetra", type: "Caviar", tag: "With smoked salmon", img: "/images/menu/caviar-1.jpg",
      desc: "An ultra-thin Parisian crêpe with sour cream, organic salad, tomatoes and a whisper of lemon, finished with smoked salmon and authentic Royal Ossetra caviar.",
      ingredients: ["Parisian crêpe", "Smoked salmon", "Sour cream", "Organic salad", "Tomatoes", "Lemon", "Royal Ossetra caviar"] },
    { name: "L'Essence d'Ossetra", type: "Caviar", tag: "Without smoked salmon", img: "/images/menu/caviar-2.jpg",
      desc: "The same crêpe with sour cream, organic salad, tomatoes and a whisper of lemon, without the smoked salmon, letting the Royal Ossetra caviar take center stage.",
      ingredients: ["Parisian crêpe", "Sour cream", "Organic salad", "Tomatoes", "Lemon", "Royal Ossetra caviar"] },
  ],
  drinks: [
    { name: "Fresh Coffee", type: "Drink", img: "/images/menu/coffee.jpg",
      ingredients: ["Freshly brewed", "The perfect crêpe companion"] },
    { name: "Chamomile Tea", type: "Drink", img: "/images/menu/tea.jpg",
      ingredients: ["Soothing natural herbal infusion"] },
    { name: "Ginger Tea", type: "Drink", img: "/images/menu/tea.jpg",
      ingredients: ["Warming", "Gently spiced"] },
  ],
};

export const tierBlurb = {
  classic: "The timeless everyday crêpes — simple, perfect, the way Brittany intended.",
  premium: "A step up: fresh fruit, premium fillings and a little more indulgence.",
  royal: "Our most lavish creations — ice cream, smoked salmon, the full experience.",
  caviar: "The crown jewel: ultra-thin crêpes finished with authentic Royal Ossetra caviar.",
  drinks: "The finishing touch to any crêpe.",
};
